name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: olagunju/simple:v1
          build-args: |
            arg1=value1
            arg2=value2
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy package to linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          scripts: |
            docker stop $(docker ps -a -q)
            docker login -u olagunju -p princeoflife430
            docker pull olagunju/simple:v1
            docker run -p 3000:8080 olagunju/simple:v1
